### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by become2019** [iliujiannan/JobSubmissionManagementSystem#1]
请问一下，这个项目在服务器上面的配置过程是怎么样的呢？可以简略叙述下吗？

**Comment by heshulin** [comment]
这个是django项目，python manage.py runserver 0.0.0.0:8000这样可以在本机8000端口上打开这个项目，当时开发环境是windows的没在linux上测试过。估计以python的兼容性应该问题不大。如果想要架设在apache上的话，博客很多，可以搜索一下。如果架设在apache上，linux的系统比较推荐。

**Comment by become2019** [comment]
@heshulin 谢谢，我去摸索下

**Comment by heshulin** [comment]
不客气 @BecomingProgrammer
